export const ACTION_LOGIN = "LOGIN";
export const ACTION_LOGOUT = "LOGOUT";
export const ACTION_USER_APARTMENT = "ACTION_USER_APARTMENT";
export const ACTION_APARTMENT_TICKETS = "APARTMENT_TICKETS";
export const ACTION_APARTMENT_DAILY_TASKS = "APARTMENT_DAILY_TASKS";
export const ACTION_APARTMENT_WEEKLY_TASKS = "APARTMENT_WEEKLY_TASKS";
export const ACTION_APARTMENT_MONTHLY_TASKS = "APARTMENT_MONTHLY_TASKS"